### ISSUE TITLE
Not working anymore "could not find results for download" TimeoutError

### ISSUE THREAD

**Issue by dflvunoooooo** [shiaky/breitbandmessung#12]
It stopped to work. If I try to measure the internet speed, it gets a time out error. Here is the log:

```
docker run -v $PWD/messprotokolle:/export/ shiaky/breitbandmessung:latest
PREPARING SPEEDTEST
RUNNING SPEEDTEST
could not find results for download
TimeoutError: Waiting for selector `#root > div > div > div > div > div.messung-options.col.col-12.text-md-right > button.px-0.px-sm-4.btn.btn-link` failed: Waiting failed: 300000ms exceeded
    at Timeout.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:64:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

```

**Comment by eogut** [comment]
I'm having the same issue. Any solutions?

**Comment by SPN34** [comment]
I'm having the same issue.

**Comment by shiaky** [comment]
Should be fixed in the new latest version of the container.
