### ISSUE TITLE
Not working on raspberry pi 4 docker

### ISSUE THREAD

**Issue by ZeeSarp** [shiaky/breitbandmessung#7]
Just leaving this here in case anyone else encounters this issue.

When I run the docker command, execution immediately fails with the following output:

```
my@name: ~ $ sudo docker run -v $PWD/messprotokolle:/export/ shiaky/breitbandmessung:latest
Error starting puppeteer
Error: Failed to launch the browser process!
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 1: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: �: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 1: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome:ELF: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 2: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: p#: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 3: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: p#: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 4: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: @l�: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 4: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: ��q: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 5: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: pX: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 6: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: pX: not found
/usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: 7: /usr/src/app/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/src/app/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Adding ```product: "chrome", executablePath: "/usr/bin/chromium",``` to the puppeteer.launch in index.js actually fixes the issue as suggested by [this post](https://stackoverflow.com/questions/60129309/puppeteer-on-raspberry-pi-zero-w).

Judging by ``` apt-get install -y procps libxss1 chromium ``` in the dockerfile, the bundled chrome installation wasn't supposed to be used if I'm not mistaken, but I didn't create a PR in case the change might break the image for platforms other than ARMv7.

Awesome project, thanks for creating this!

**Comment by shiaky** [comment]
Hi, thanks for reporting it. Please feel free to create a PR. I will try it on an i86 machine.
